name: example
description: Charts-Flutter Demo
version: 0.0.1

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.5.0'

dependencies:
  charts_flutter:
    path: ../
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ">=1.1.1 <2.0.0"
  intl: ">=0.17.0 <1.0.0"

dev_dependencies: 
  flutter_test:
    sdk: flutter
  test: 

flutter:
  uses-material-design: true
