name: example
description: Charts-Flutter Demo
version: 0.0.1

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: '>=3.0.2'

dependencies:
  charts_flutter:
    path: ../
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.12.0
  intl: "0.19.0"
flutter:
  uses-material-design: true
