name: charts_common
version: 0.13.0
description: A common library for charting packages.
homepage: https://github.com/google/charts

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  collection: ^1.18.0
  intl: "0.19.0"
  logging: ^1.2.0
  meta: ^1.15.0
  vector_math: ^2.0.8

dev_dependencies:
  mockito: ^5.4.4
  test: ^1.25.7
