name: charts_flutter
version: 0.13.0
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  charts_common:
    # path: ../charts_common/
    git:
      url: https://github.com/italo-patricio/charts.git
      path: charts_common
  collection: ">=0.14.5 <2.0.0"
  meta: ">=1.1.1 <2.0.0"
  intl: "0.19.0"
  logging: ^1.2.0

dev_dependencies:
  mockito: ^5.3.2
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  test: ^1.22.0